import { T } from "./siteConfig.js";

export const GALLERY_TAGS = ["All", "KIND", "KINGs", "Daniel Fast", "FACE", "P119", "TJC", "CST", "gDX"];

export const GALLERY_PHOTOS = [
  {
    id: 1,
    src: "/photos/KIN_programs.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, ${T.green} 0%, ${T.greenD} 100%)`,
    caption: "KIND Daily Devotional — goDs in character session",
    tag: "KIND",
    date: "March 2025",
  },
  {
    id: 2,
    src: "/photos/Epic_moments.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, #7B2D8B 0%, #4A1B55 100%)`,
    caption: "KINGs 002 Cell — Sunday mentorship circle",
    tag: "KINGs",
    date: "February 2025",
  },
  {
    id: 3,
    src: "/photos/Daniel_Fast.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, ${T.gold} 0%, ${T.goldD} 100%)`,
    caption: "Daniel Fast Week 3 — 637 participants, 200% growth",
    tag: "Daniel Fast",
    date: "January 2025",
  },
  {
    id: 4,
    src: "/photos/FACE_Feed_A_Community_EveryWeek.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, #D94F30 0%, #A83920 100%)`,
    caption: "FACE — feeding the community every Sunday",
    tag: "FACE",
    date: "April 2025",
  },
  {
    id: 5,
    src: "/photos/P119_Academy.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, #0071E3 0%, #004C99 100%)`,
    caption: "P119 Academy — Mathematics & Character class",
    tag: "P119",
    date: "May 2025",
  },
  {
    id: 6,
    src: "/photos/Community_impact.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, #8B4513 0%, #5C2D0A 100%)`,
    caption: "The Jesus Christ Concert 2025 — Annual celebration",
    tag: "TJC",
    date: "December 2025",
  },
  {
    id: 7,
    src: "/photos/Spirit_Filled_Parents.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, #27AE60 0%, #1A6B3C 100%)`,
    caption: "Covenant Servants — volunteer formation session",
    tag: "CST",
    date: "October 2025",
  },
  {
    id: 8,
    src: "/photos/Skills_Development.jpg",
    width: 1600,
    height: 1067,
    gradient: `linear-gradient(135deg, ${T.goldL} 0%, ${T.gold} 100%)`,
    caption: "goDxperience — Sunday faith formation gathering",
    tag: "gDX",
    date: "June 2025",
  },
];
